version: '3'

services:
  app1:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "3800:3800"

  app2:
    build:
      context: ./socket
      dockerfile: Dockerfile
    ports:
      - "8800:8800"
